name: Build and Release APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-release:
    permissions: write-all
    env:
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ env.AUTH_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: latest
          release_name: latest Release
          body: |
            Latest apk
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          asset_path: app/build/outputs/apk/release/app-release-unsigned.apk
          asset_name: app-release-unsigned.apk
          asset_content_type: application/vnd.android.package-archive
          release_id: ${{ steps.create_release.outputs.release_id }}
          token: ${{ env.AUTH_TOKEN }}
